events:
  - name: "CPI"
    impact: "high"
    datetime_utc: "2026-05-13T12:30:00"
  - name: "PPI"
    impact: "high"
    datetime_utc: "2026-05-14T12:30:00"
  - name: "FOMC"
    impact: "high"
    datetime_utc: "2026-06-18T18:00:00"
  - name: "NFP"
    impact: "high"
    datetime_utc: "2026-06-06T12:30:00"
  - name: "PCE"
    impact: "high"
    datetime_utc: "2026-05-30T12:30:00"
  - name: "CPI"
    impact: "high"
    datetime_utc: "2026-06-11T12:30:00"
  - name: "FOMC"
    impact: "high"
    datetime_utc: "2026-07-30T18:00:00"
  - name: "FOMC"
    impact: "high"
    datetime_utc: "2026-09-17T18:00:00"
  - name: "FOMC"
    impact: "high"
    datetime_utc: "2026-11-05T18:00:00"
